export const countryFlags: Record<string, string> = {
  Kenya: '🇰🇪',
  Tanzania: '🇹🇿',
  Uganda: '🇺🇬',
  Somalia: '🇸🇴',
  Djibouti: '🇩🇯',
  Ethiopia: '🇪🇹',
  Rwanda: '🇷🇼',
  'Saudi Arabia': '🇸🇦',
  UAE: '🇦🇪',
  'United Arab Emirates': '🇦🇪',
  Egypt: '🇪🇬',
  Nigeria: '🇳🇬',
  'South Africa': '🇿🇦',
  Qatar: '🇶🇦',
  Morocco: '🇲🇦',
  Tunisia: '🇹🇳',
  Algeria: '🇩🇿',
  Jordan: '🇯🇴',
  Kuwait: '🇰🇼',
  Bahrain: '🇧🇭',
  Oman: '🇴🇲',
};

export const partnerCountries = [
  { name: 'Kenya', flag: '🇰🇪' },
  { name: 'Tanzania', flag: '🇹🇿' },
  { name: 'Uganda', flag: '🇺🇬' },
  { name: 'Somalia', flag: '🇸🇴' },
  { name: 'Djibouti', flag: '🇩🇯' },
  { name: 'Ethiopia', flag: '🇪🇹' },
  { name: 'Rwanda', flag: '🇷🇼' },
  { name: 'Saudi Arabia', flag: '🇸🇦' },
  { name: 'UAE', flag: '🇦🇪' },
  { name: 'Egypt', flag: '🇪🇬' },
  { name: 'Nigeria', flag: '🇳🇬' },
  { name: 'South Africa', flag: '🇿🇦' },
  { name: 'Qatar', flag: '🇶🇦' },
  { name: 'Morocco', flag: '🇲🇦' },
  { name: 'Oman', flag: '🇴🇲' },
  { name: 'Bahrain', flag: '🇧🇭' },
];
